spring.application.name=software2
spring.datasource.url=jdbc:mysql://localhost:3308/clinic?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate: genera las tablas a partir de las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081

# JWT secret para firma HS256 (mínimo 32 caracteres)
jwt.secret=Gp7s9FQ2eL98xF0zH3KaP1tQwS7rJ9uM4vN2gC8bZ5qD1fE6sA9kB3qW0tY2
1